export interface CuratedEmoji {
  emoji: string
  keywords: string[]
}

// ~50 emojis useful for AI-agent identities. Keywords drive the search filter.
// The set exceeds the "50+" assertion in the picker test.
export const AGENT_EMOJIS: CuratedEmoji[] = [
  { emoji: '🔍', keywords: ['search', 'investigate', 'find'] },
  { emoji: '⚡', keywords: ['fast', 'energy', 'quick'] },
  { emoji: '🩺', keywords: ['health', 'doctor', 'therapist'] },
  { emoji: '📋', keywords: ['plan', 'list', 'clipboard'] },
  { emoji: '✉️', keywords: ['email', 'mail', 'message'] },
  { emoji: '🐛', keywords: ['bug', 'debug', 'error'] },
  { emoji: '🎯', keywords: ['target', 'goal', 'focus'] },
  { emoji: '🧠', keywords: ['think', 'brain', 'mind'] },
  { emoji: '📚', keywords: ['books', 'library', 'docs'] },
  { emoji: '🪄', keywords: ['magic', 'wand', 'wizard'] },
  { emoji: '⚙️', keywords: ['settings', 'gear', 'config'] },
  { emoji: '🎨', keywords: ['art', 'design', 'paint'] },
  { emoji: '💡', keywords: ['idea', 'light', 'insight'] },
  { emoji: '🌟', keywords: ['star', 'special', 'favorite'] },
  { emoji: '🔥', keywords: ['fire', 'hot', 'urgent'] },
  { emoji: '🚀', keywords: ['rocket', 'launch', 'fast'] },
  { emoji: '👁️', keywords: ['watch', 'observe', 'eye'] },
  { emoji: '🤖', keywords: ['robot', 'ai', 'bot'] },
  { emoji: '📝', keywords: ['note', 'write', 'memo'] },
  { emoji: '🎭', keywords: ['drama', 'role', 'persona'] },
  { emoji: '🗂️', keywords: ['organize', 'sort', 'files'] },
  { emoji: '⏱️', keywords: ['time', 'fast', 'timer'] },
  { emoji: '🧩', keywords: ['puzzle', 'solve', 'piece'] },
  { emoji: '🛠️', keywords: ['tools', 'build', 'fix'] },
  { emoji: '📊', keywords: ['chart', 'data', 'analytics'] },
  { emoji: '🎓', keywords: ['teach', 'tutor', 'graduate'] },
  { emoji: '🏗️', keywords: ['architecture', 'build', 'construct'] },
  { emoji: '🔧', keywords: ['fix', 'wrench', 'repair'] },
  { emoji: '🧪', keywords: ['experiment', 'test', 'science'] },
  { emoji: '⚖️', keywords: ['judge', 'balance', 'fair'] },
  { emoji: '🗣️', keywords: ['speak', 'talk', 'voice'] },
  { emoji: '👂', keywords: ['listen', 'hear', 'ear'] },
  { emoji: '🧭', keywords: ['compass', 'direction', 'guide'] },
  { emoji: '🗺️', keywords: ['map', 'navigate', 'explore'] },
  { emoji: '📦', keywords: ['package', 'box', 'ship'] },
  { emoji: '🌱', keywords: ['grow', 'start', 'beginner'] },
  { emoji: '🌳', keywords: ['tree', 'nature', 'structure'] },
  { emoji: '🌊', keywords: ['wave', 'flow', 'ocean'] },
  { emoji: '🔮', keywords: ['predict', 'future', 'crystal'] },
  { emoji: '📐', keywords: ['precise', 'measure', 'design'] },
  { emoji: '🪙', keywords: ['money', 'cost', 'coin'] },
  { emoji: '⏰', keywords: ['alarm', 'time', 'remind'] },
  { emoji: '🧹', keywords: ['clean', 'sweep', 'tidy'] },
  { emoji: '🪞', keywords: ['mirror', 'reflect', 'self'] },
  { emoji: '🧱', keywords: ['build', 'brick', 'foundation'] },
  { emoji: '🪜', keywords: ['ladder', 'step', 'climb'] },
  { emoji: '🎁', keywords: ['gift', 'surprise', 'present'] },
  { emoji: '🪧', keywords: ['sign', 'announce', 'notice'] },
  { emoji: '🧰', keywords: ['toolbox', 'kit', 'utility'] },
  { emoji: '🗒️', keywords: ['notepad', 'jot', 'note'] },
]
